### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by tlc** [mattwelch/sonospowermate#2]
I'm not sure, this might be from trying "next track" while pandora was playing.

````
$ node so*
Server respond 404
Server respond 404

TypeError: Cannot call method 'trim' of null
    at cleanProtocol (/Users/troy/SONOS/sonospowermate/node_modules/wget/lib/wget.js:154:16)
    at Object.download (/Users/troy/SONOS/sonospowermate/node_modules/wget/lib/wget.js:21:23)
    at /Users/troy/SONOS/sonospowermate/sonospowermate.js:259:29
    at Request._callback (/Users/troy/SONOS/sonospowermate/node_modules/node-tts-api/node-tts-api.js:13:14)
    at Request.self.callback (/Users/troy/SONOS/sonospowermate/node_modules/node-tts-api/node_modules/request/main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/troy/SONOS/sonospowermate/node_modules/node-tts-api/node_modules/request/main.js:661:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/troy/SONOS/sonospowermate/node_modules/node-tts-api/node_modules/request/main.js:623:14)
    at IncomingMessage.emit (events.js:117:20)
`````

**Comment by tlc** [comment]
Also seeing

````
$ node so*
Server respond 404
Server respond 404

/Users/troy/SONOS/sonospowermate/node_modules/node-powermate/powermate.js:55
  this._hidDevice.sendFeatureReport(featureReport);
                  ^
could not send feature report to device
````
